# Generated by Django 4.2.2 on 2023-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_mabani'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabani',
            name='image_fore',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mabani',
            name='image_one',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mabani',
            name='image_three',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mabani',
            name='image_tow',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='estate_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='estate_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='neighborhood',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='prise',
            field=models.IntegerField(null=True),
        ),
    ]
