# Generated by Django 4.2.2 on 2023-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_mabani_image_fore_mabani_image_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabani',
            name='Description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='estate_type',
            field=models.CharField(choices=[('أرض', 'أرض'), ('شقة', 'شقة'), ('فيلا', 'فيلا'), ('محل', 'محل')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='name',
            field=models.CharField(choices=[('بيع', 'بيع'), ('آجار', 'آجار'), (' رهن', ' رهن')], max_length=255),
        ),
    ]
