# Generated by Django 4.2.2 on 2023-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_motorbike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='mabani',
            name='image_fore',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='mabani',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
