# Generated by Django 4.2.2 on 2023-07-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_kitchen_tools_alter_car_image_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical_tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(choices=[('مدينة ديرالزور', 'مدينة ديرالزور'), ('موحسن', 'موحسن'), ('ابوعمر', 'ابوعمر'), ('العبد', 'العبد'), ('البوليل', 'البوليل'), ('الطوب', 'الطوب'), ('الزباري', 'الزباري'), ('سعلو', 'سعلو'), ('مدينة الميادين', 'مدينة الميادين'), ('محكان', 'محكان'), ('القورية', 'القورية'), ('عشارة ', 'عشارة '), ('غريبه', 'غريبه'), ('تشرين', 'تشرين'), ('صبيخان', 'صبيخان'), ('دوير', 'دوير'), ('مدينة البوكمال', 'مدينة البوكمال')], max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('neighborhood', models.CharField(max_length=255, null=True)),
                ('phone_owner', models.CharField(max_length=10)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='kitphoto')),
                ('image_tow', models.ImageField(blank=True, null=True, upload_to='kitphoto')),
            ],
        ),
        migrations.CreateModel(
            name='House_tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(choices=[('مدينة ديرالزور', 'مدينة ديرالزور'), ('موحسن', 'موحسن'), ('ابوعمر', 'ابوعمر'), ('العبد', 'العبد'), ('البوليل', 'البوليل'), ('الطوب', 'الطوب'), ('الزباري', 'الزباري'), ('سعلو', 'سعلو'), ('مدينة الميادين', 'مدينة الميادين'), ('محكان', 'محكان'), ('القورية', 'القورية'), ('عشارة ', 'عشارة '), ('غريبه', 'غريبه'), ('تشرين', 'تشرين'), ('صبيخان', 'صبيخان'), ('دوير', 'دوير'), ('مدينة البوكمال', 'مدينة البوكمال')], max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('neighborhood', models.CharField(max_length=255, null=True)),
                ('phone_owner', models.CharField(max_length=10)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_tow', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='house')),
                ('image_fore', models.ImageField(blank=True, null=True, upload_to='house')),
            ],
        ),
        migrations.RemoveField(
            model_name='kitchen_tools',
            name='image_fore',
        ),
        migrations.RemoveField(
            model_name='kitchen_tools',
            name='image_three',
        ),
        migrations.AlterField(
            model_name='car',
            name='image_fore',
            field=models.ImageField(blank=True, null=True, upload_to='carphoto'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='carphoto'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to='carphoto'),
        ),
        migrations.AlterField(
            model_name='kitchen_tools',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='kitchenphoto'),
        ),
        migrations.AlterField(
            model_name='kitchen_tools',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to='kitchenphoto'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='image_fore',
            field=models.ImageField(blank=True, null=True, upload_to='motorphoto'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='motorphoto'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='motorphoto'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to='motorphoto'),
        ),
    ]
