# Generated by Django 4.2.2 on 2023-07-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more'),
        ('members', '0013_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabani',
            name='hit_count_generic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hit_count_generic', to='hitcount.hitcount'),
        ),
    ]
